version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: sign-mysql
    volumes:
      - ./pkg/mysql:/docker-entrypoint-initdb.d
    ports:
      - "9910:3306"
    environment:
      - MYSQL_DATABASE=sign
      - MYSQL_USER=yogen
      - MYSQL_PASSWORD=yogen123
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"
    command:
      -  --default-authentication-plugin=mysql_native_password
  redis:
    image: redis:latest
    container_name: sign-redis
    ports:
      - "9911:6379"
  rabbitmq:
    image: rabbitmq:management
    container_name: sign-rabbitmq
    ports:
      - "9912:5672"
      - "9913:15672"
    environment:
      - RABBITMQ_DEFAULT_USER:yogen
      - RABBITMQ_DEFAULT_PASS:yogen123
      - RABBITMQ_DEFAULT_VHOST:sign
  etcd:
    image: quay.io/coreos/etcd:v3.5.5
    container_name: sign-etcd
    environment:
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
      - ETCDCTL_API=3
    ports:
      - "9914:2379"
  nginx:
    image: nginx:1.21
    container_name: sign-nginx
    ports:
      - 80:80
    volumes:
      - ./pkg/nginx/conf/nginx.conf:/etc/nginx/nginx.conf