// Code generated by hertz generator.

package main

import (
	"fmt"
	"sign/conf"
	"sign/utils"
)

func main() {
	//h := server.Default()
	//
	//register(h)
	//h.Spin()
	config := conf.NewConfig()
	flow := utils.NewSnowFlow(config.SnowFlow)
	fmt.Println(flow.GenID())
}
