// Code generated by hertz generator.

// Code generated by hertz generator.

package main

import (
	"flag"
	"github.com/cloudwego/hertz/pkg/app/server"
	"sign/conf"
	"sign/services/base"
	"sign/services/choose"
	"sign/services/sign"
)

func main() {
	config := conf.GlobalConfig
	var serviceName string
	flag.StringVar(&serviceName, "service", config.DSN.ApiServiceName, "启动服务名")
	flag.Parse()
	switch serviceName {
	case config.DSN.ApiServiceName:
		h := server.Default(server.WithHostPorts(config.DSN.ApiService))
		register(h)
		h.Spin()
	case config.DSN.BaseServiceName:
		base.BaseServiceStart(config)
	case config.DSN.SignServiceName:
		sign.SignServiceStart(config)
	case config.DSN.ChooseServiceName:
		choose.ChooseServiceStart(config)
	}
}
