version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: sign-mysql
    volumes:
      - ../pkg/mysql:/docker-entrypoint-initdb.d
    ports:
      - "9910:3306"
    environment:
      - MYSQL_DATABASE=sign
      - MYSQL_USER=yogen
      - MYSQL_PASSWORD=yogen123
      - MYSQL_RANDOME_ROOT_PASSWORD="yes"
    command:
      -  --default-authentication-plugin=mysql_native_password
  redis:
    image: redis:latest
    container_name: sign-redis
    ports:
      - "9911:6379"
