// Code generated by Kitex v0.7.2. DO NOT EDIT.
package chooseservice

import (
	server "github.com/cloudwego/kitex/server"
	choose "sign/kitex_gen/sign/choose"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler choose.ChooseService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
